crtns=['Tom nd Jerry','dora','shinchan','shinchan','doremon','krishna']
print(crtns)
print("--------------------------------------------")
print("After appending")
crtns.append('ben10')
print(crtns)
print("--------------------------------------------")
print("After inserting")
crtns.insert(3,'balaram')
print(crtns)
print("--------------------------------------------")
print("After removing")
crtns.remove('ben10')
print(crtns)
print("--------------------------------------------")
print("After pop an element")
crtns.pop(5)
print(crtns)
print("--------------------------------------------")
print(crtns.index('dora'))
print("--------------------------------------------")
print("After reversing")
crtns.reverse()
print(crtns)
print("--------------------------------------------")
cnt=crtns.count('krishna')
print(cnt)
print("--------------------------------------------")
a=['N','I','K','k','i']
a.sort()
print(a)
print("--------------------------------------------")
crtns.sort()
print(crtns)
print("--------------------------------------------")
crtns.clear()
print(crtns)