proglang=['c','c++','python','java','php','flutter']
print(proglang)
print(type(proglang))
print("---------------------------")
print("Accessing positive elements")
print(proglang[0])
print(proglang[1])
print(proglang[2])
print(proglang[3])
print(proglang[4])
print(proglang[5])
print("Accesing negative  elements")
print(proglang[-6])
print(proglang[-5])
print(proglang[-4])
print(proglang[-3])
print(proglang[-2])
print(proglang[-1])

